import numpy as np

array_0d = np.array(100)
array_1d = np.array([1,2,3,4,5])
array_2d = np.array([[1,2,3],[10,20,30]])
array_3d = np.array([[[1,2,3],[10,20,30]],[[4,5,6],[100,200,300]]])

print(f'value of array_0d: {array_0d}')
print(f'dimension of array_0d: {array_0d.ndim}')
print(f'shape of array_0d: {array_0d.shape}')
print(f'type of array_0d: {array_0d.dtype}')
print(f'value of array_1d: {array_1d}')
print(f'dimension of array_1d: {array_1d.ndim}')
print(f'shape of array_1d: {array_1d.shape}')
print(f'type of array_1d: {array_1d.dtype}')
print(f'value of array_2d: {array_2d}')
print(f'dimension of array_2d: {array_3d.ndim}')
print(f'shape of array_2d: {array_3d.shape}')
print(f'type of array_2d: {array_2d.dtype}')
print(f'value of array_3d: {array_3d}')
print(f'dimension of array_3d: {array_3d.ndim}')
print(f'shape of array_3d: {array_3d.shape}')
print(f'type of array_3d: {array_3d.dtype}')